### PR TITLE
Base Asset SRC-20 Contract

### LINKED ISSUE #160: Base Asset Contract
Create a base asset contract for ether

### PR DESCRIPTION
**Pull request by bitzoic**
# Description

Adds the SRC-20 implementation contract for the Fuel Network's Base Asset, Ether. 

Uses fuel-core v0.26.0 and forc v0.56.1

# Closes

Closes #160

### CODE REVIEW

**Review by dmihal — APPROVED** [review]

**Comment by bitzoic** [comment]
Dependent on https://github.com/FuelLabs/fuel-bridge/pull/180

**Review by luizstacio — APPROVED** [review]

**Review by DefiCake — APPROVED** [review]
lgtm

**Review by DefiCake — COMMENTED** [review]
I would only add to double check that the binary has been generated with `--release`.

**Comment by bitzoic** [comment]
> I would only add to double check that the binary has been generated with `--release`.

Release is used in the const for the bytecode path https://github.com/FuelLabs/fuel-bridge/blob/3aaaaf43abdd8de1f780c8a189ad4818c283e7dc/packages/base-asset/tests/harness.rs#L12

**Comment by DefiCake** [comment]
I just checked manually, we are good to go 👍🏻

**Pull request merged**
